version: 0.2

phases:
  install:
    commands:
      - pwd
      - ls -la
      - ls -la ~
      - ls -la /
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cd build && zip -r9 ../jar_website.zip . ; cd ..
      - |
        for lambda in `ls jar_lambda_*.py`
        do
          mv $lambda index.py
          zipfile=`echo $lambda |sed 's/\.py$/.zip/'`
          zip -9 $zipfile index.py
          grep cfnresponse index.py >/dev/null && zip -9 $zipfile cfnresponse.py
        done
artifacts:
  files:
    - '*.zip'
cache:
  paths:
    - 'node_modules/**/*'
