Resources:
  SourceCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
  SourceCodeToS3:
    Type: Custom::SourceUploader
    Properties:
      ServiceToken: !GetAtt LambdaSourceCodeFuction.Arn
      Functions:
        -
          Name: jar_lambda_ami.py
          Code: !Sub |
            jar_lambda_ami.py
        -
          Name: jar_lambda_auth.py
          Code: |
            jar_lambda_auth.py
        -
          Name: jar_lambda_list_jars.py
          Code: |
            jar_lambda_list_jars.py
        -
          Name: jar_lambda_newpass.py
          Code: |
            jar_lambda_newpass.py
        -
          Name: jar_lambda_notify.py
          Code: |
            jar_lambda_notify.py
        -
          Name: jar_lambda_schedule.py
          Code: |
            jar_lambda_schedule.py
  LambdaSourceCodeFuction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.6
      Handler: index.handler
      Role: !GetAtt LambdaSourceCodeRole.Arn
      Timeout: 300
      Environment:
        Variables:
          JAR_LAMBDA_SOURCECODE_BUCKET: !Ref SourceCodeBucket
      Code:
        ZipFile: |
          jar_lambda_sourcecode.py
  LambdaSourceCodeRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: PutToSourceCodeBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: s3:ListBucket
                Resource: !GetAtt SourceCodeBucket.Arn
              -
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub
                  - ${SourceCodeBucket}/*
                  - SourceCodeBucket: !GetAtt SourceCodeBucket.Arn
